# Generated by Django 4.1.2 on 2024-07-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankProfile',
        ),
    ]
