# Generated by Django 4.1.2 on 2024-07-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_config', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankcard',
            table='bank_cards',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
